name: Docker Image CI

on:
  push:
    branches: [main] 
  pull_request:
    branches: [main]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --tag=prpa1984/clientes:1.0.0
    - uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKER_LOGIN_USERNAME }}
        password: ${{ secrets.DOCKER_LOGIN_PASSWORD }}
    - name: Push the Docker image
      run: docker push prpa1984/clientes:1.0.0
